/**
 * Unit tests for the skill generator.
 *
 * The generator is the only thing standing between the registries and what an
 * agent reads, so its formatting rules deserve the same treatment as library
 * code. Nothing here calls an agent; see eval/ for that.
 */

import { describe, it, expect } from 'vitest';
import { withTableOfContents, TOC_LINE_THRESHOLD, buildOutputs, findStaleOutputs } from '../../scripts/generate-skills.ts';

function longDoc(sections: string[], filler = 200): string {
  const body = sections.map((s) => `## ${s}\n\n${'text\n'.repeat(filler / sections.length)}`).join('\n');
  return `# Title\n\n${body}`;
}

describe('withTableOfContents', () => {
  it('leaves short files alone', () => {
    const short = '# Title\n\n## One\n\ntext\n\n## Two\n\ntext';
    expect(withTableOfContents(short)).toBe(short);
  });

  it('adds a contents list to long files', () => {
    const result = withTableOfContents(longDoc(['Alpha', 'Beta', 'Gamma']));

    expect(result).toContain('## Contents');
    expect(result).toContain('- [Alpha](#alpha)');
    expect(result).toContain('- [Beta](#beta)');
    expect(result).toContain('- [Gamma](#gamma)');
  });

  it('inserts the contents directly after the title', () => {
    const lines = withTableOfContents(longDoc(['Alpha', 'Beta'])).split('\n');
    const titleIndex = lines.findIndex((l) => l.startsWith('# '));
    const tocIndex = lines.findIndex((l) => l === '## Contents');

    expect(tocIndex).toBeGreaterThan(titleIndex);
    expect(tocIndex - titleIndex).toBeLessThanOrEqual(3);
  });

  it('does not index a long file with a single section', () => {
    const result = withTableOfContents(`# Title\n\n## Only\n\n${'text\n'.repeat(200)}`);
    expect(result).not.toContain('## Contents');
  });

  it('slugs headings the way markdown anchors do', () => {
    const result = withTableOfContents(longDoc(['Value Fields', '`input` and friends', 'Q&A: edge cases']));

    expect(result).toContain('- [Value Fields](#value-fields)');
    expect(result).toContain('- [`input` and friends](#input-and-friends)');
    expect(result).toContain('- [Q&A: edge cases](#qa-edge-cases)');
  });

  it('ignores heading levels other than h2', () => {
    const result = withTableOfContents(longDoc(['Alpha', 'Beta', 'Gamma']).replace('## Beta', '### Beta'));

    expect(result).toContain('- [Alpha](#alpha)');
    expect(result).toContain('- [Gamma](#gamma)');
    expect(result).not.toContain('- [Beta]');
  });

  it('uses a threshold consistent with the documented one', () => {
    expect(TOC_LINE_THRESHOLD).toBe(100);
  });
});

describe('generated outputs', () => {
  it('produces the five expected files', async () => {
    const outputs = await buildOutputs();
    const names = outputs.map(([path]) => path.split('/').slice(-2).join('/'));

    expect(names).toEqual([
      'dynamic-forms/SKILL.md',
      'references/rules.md',
      'references/field-types.md',
      'references/patterns.md',
      'references/pitfalls.md',
    ]);
  });

  it('marks every file as generated', async () => {
    for (const [path, contents] of await buildOutputs()) {
      expect(contents, `${path} is missing the generated marker`).toContain('Generated by scripts/generate-skills.ts');
    }
  });

  it('escapes pipes so union types do not break tables', async () => {
    const outputs = await buildOutputs();
    const fieldTypes = outputs.find(([p]) => p.endsWith('field-types.md'))![1];

    // The `input` field's `type` prop is a union; its pipes must be escaped
    // or the markdown table gains phantom columns.
    const typeRow = fieldTypes.split('\n').find((l) => l.startsWith('| `type`'));
    expect(typeRow).toBeDefined();
    expect(typeRow).toContain('\\|');
  });

  it('never emits an empty code block', async () => {
    const outputs = await buildOutputs();
    for (const [path, contents] of outputs) {
      expect(contents, `${path} has an empty typescript block`).not.toMatch(/```typescript\n\s*```/);
    }
  });

  it('gives every long reference file a table of contents', async () => {
    const outputs = await buildOutputs();

    for (const [path, contents] of outputs) {
      if (!path.includes('/references/')) continue;
      if (contents.split('\n').length <= TOC_LINE_THRESHOLD) continue;

      const hasHeadingToc = contents.includes('## Contents');
      const hasLinkedTable = /^\| \[`/m.test(contents);

      expect(hasHeadingToc || hasLinkedTable, `${path} is long but has no contents index`).toBe(true);
    }
  });

  it('reports no staleness against the committed files', async () => {
    expect(await findStaleOutputs()).toEqual([]);
  });
});
