// Global type declarations for Angular 21 modules to fix Jest module resolution
// This file is automatically generated by patch-angular-jest-modules.sh

declare module '@angular/core/rxjs-interop' {
  import type { OutputEmitterRef } from '@angular/core';
  import type { Observable } from 'rxjs';

  export function outputFromObservable<T>(observable: Observable<T>): OutputEmitterRef<T>;
}

declare module '@angular/forms/signals' {
  import type { ModelSignal } from '@angular/core';

  export interface FormValueControl<T = any> {
    value: ModelSignal<T>;
    disabled?: any;
    errors?: any;
  }

  export interface FormCheckboxControl {
    checked: ModelSignal<boolean>;
    disabled?: any;
    errors?: any;
  }
}
