openapi: '3.0.3'
info:
  title: Test
  version: '1.0.0'
paths:
  /profiles:
    post:
      operationId: createProfile
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                address:
                  type: object
                  properties:
                    street:
                      type: string
                    city:
                      type: string
                    zip:
                      type: string
      responses:
        '201':
          description: Created
