openapi: '3.0.3'
info:
  title: Test
  version: '1.0.0'
paths:
  /contacts:
    post:
      operationId: createContact
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email]
              properties:
                email:
                  type: string
                  format: email
                username:
                  type: string
                  minLength: 3
                  maxLength: 20
                  pattern: '^[a-z]+$'
                score:
                  type: integer
                  minimum: 0
                  maximum: 100
      responses:
        '201':
          description: Created
