name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: '[Feature]: '
labels: ['enhancement', 'needs-triage']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out this form as completely as possible.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: |
        Is your feature request related to a problem? Please describe.
        Ex. I'm always frustrated when...
      placeholder: |
        I want to be able to... but currently there's no way to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: |
        I would like to have a feature that allows...

        Example usage:
        ```typescript
        const config = {
          fields: [
            { key: 'email', type: 'input', newFeature: true }
          ]
        };
        ```
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: |
        - Alternative 1: ...
        - Alternative 2: ...
        - Current workaround: ...
    validations:
      required: false

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New field type
        - New UI adapter
        - Core library enhancement
        - Validation feature
        - Conditional logic feature
        - Performance improvement
        - Developer experience
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: package
    attributes:
      label: Which package should this be added to?
      multiple: true
      options:
        - '@ng-forge/dynamic-forms (core)'
        - '@ng-forge/dynamic-forms-material'
        - '@ng-forge/dynamic-forms-primeng'
        - '@ng-forge/dynamic-forms-ionic'
        - '@ng-forge/dynamic-forms-bootstrap'
        - 'New package'
        - 'Documentation'
        - 'Not sure'
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe the use cases for this feature
      placeholder: |
        1. As a developer, I want to... so that...
        2. When building forms for..., I need to...
        3. This would help with...
    validations:
      required: true

  - type: textarea
    id: api-design
    attributes:
      label: Proposed API / Design
      description: If you have ideas about how this could be implemented, share them here
      render: typescript
      placeholder: |
        // Proposed configuration
        interface NewFeatureConfig {
          enabled: boolean;
          options?: {
            // ...
          };
        }

        // Usage
        const field = {
          key: 'myField',
          type: 'input',
          newFeature: {
            enabled: true,
            options: { }
          }
        };
    validations:
      required: false

  - type: dropdown
    id: breaking-change
    attributes:
      label: Breaking Change?
      description: Would this require breaking changes to the API?
      options:
        - 'No'
        - 'Yes'
        - 'Not sure'
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - 'Nice to have'
        - 'Important'
        - 'Critical'
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request
      placeholder: |
        - Similar feature in other libraries: ...
        - Real-world example: ...
        - Related issues: #123, #456
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to contribute to this feature?
      options:
        - label: I am willing to submit a PR to implement this feature
          required: false
        - label: I can help with testing
          required: false
        - label: I can help with documentation
          required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have checked the documentation to ensure this feature doesn't already exist
          required: true
        - label: I have provided clear use cases for this feature
          required: true
