import { FormConfig } from '@ng-forge/dynamic-forms';
import { ExampleScenario } from '../shared/types';

export const valueDerivationScenario: ExampleScenario = {
  id: 'value-derivation',
  title: 'Value Derivation',
  description: 'Demonstrates automatic value derivation using expressions to calculate totals and concatenate strings.',
  config: {
    fields: [
      {
        key: 'calculationTitle',
        type: 'text',
        label: 'Order Calculator',
        props: { elementType: 'h3' },
      },
      {
        key: 'quantity',
        type: 'input',
        label: 'Quantity',
        value: 1,
        min: 1,
        props: { type: 'number' },
        col: 4,
      },
      {
        key: 'unitPrice',
        type: 'input',
        label: 'Unit Price ($)',
        value: 25,
        props: { type: 'number' },
        col: 4,
      },
      {
        key: 'subtotal',
        type: 'input',
        label: 'Subtotal ($)',
        props: { type: 'number' },
        disabled: true,
        col: 4,
        derivation: 'formValue.quantity * formValue.unitPrice',
      },
      {
        key: 'taxRate',
        type: 'input',
        label: 'Tax Rate (%)',
        value: 10,
        props: { type: 'number' },
        col: 4,
      },
      {
        key: 'tax',
        type: 'input',
        label: 'Tax ($)',
        props: { type: 'number' },
        disabled: true,
        col: 4,
        derivation: 'formValue.subtotal * formValue.taxRate / 100',
      },
      {
        key: 'total',
        type: 'input',
        label: 'Total ($)',
        props: { type: 'number' },
        disabled: true,
        col: 4,
        derivation: 'formValue.subtotal + formValue.tax',
      },
      {
        key: 'nameTitle',
        type: 'text',
        label: 'Name Concatenation',
        props: { elementType: 'h3' },
      },
      {
        key: 'firstName',
        type: 'input',
        label: 'First Name',
        value: 'John',
        col: 4,
      },
      {
        key: 'lastName',
        type: 'input',
        label: 'Last Name',
        value: 'Doe',
        col: 4,
      },
      {
        key: 'fullName',
        type: 'input',
        label: 'Full Name',
        disabled: true,
        col: 4,
        derivation: '(formValue.firstName || "") + " " + (formValue.lastName || "")',
      },
    ],
  } as const satisfies FormConfig,
};
