import type { Tree } from '@nx/devkit';
import type { SyncGeneratorResult } from 'nx/src/utils/sync-generators';

/**
 * Sync generator for packages/dynamic-forms/internal/src/public_api.ts:
 * `export *` from every non-spec module in internal/src/lib. Same-binding
 * re-export duplicates are fine; only genuinely distinct same-name exports
 * collide (the build will name them, exclude as needed).
 */
const LIB = 'packages/dynamic-forms/internal/src/lib';
const OUT = 'packages/dynamic-forms/internal/src/public_api.ts';
const EXCLUDE = new Set<string>(); // module relpaths (no ext) to skip on collision

const isSkip = (f: string) => f.endsWith('.spec.ts') || f.endsWith('.type-test.ts');

function walk(tree: Tree, dir: string, acc: string[] = []): string[] {
  for (const name of tree.children(dir)) {
    const path = `${dir}/${name}`;
    if (!tree.isFile(path)) walk(tree, path, acc);
    else if (path.endsWith('.ts') && !isSkip(path)) acc.push(path);
  }
  return acc;
}

const HEADER = `/**
 * @ng-forge/dynamic-forms/internal
 *
 * BUILD-TIME FOUNDATION ENTRYPOINT — not a supported public API, no semver guarantee.
 * Shared compiled DI tokens / services / config types for the consumer
 * (\`@ng-forge/dynamic-forms\`) and adapter-author (\`@ng-forge/dynamic-forms/integration\`)
 * entrypoints, so tokens keep a single identity across bundles.
 *
 * Form consumers  -> '@ng-forge/dynamic-forms'
 * Adapter authors -> '@ng-forge/dynamic-forms/integration'
 *
 * AUTO-GENERATED by the gen-public-api sync generator (tools/workspace-plugin) — run \`nx sync\` to update.
 */\n\n`;

export default function genPublicApiGenerator(tree: Tree): SyncGeneratorResult {
  const hasExport = (f: string) => /\bexport\b/.test(tree.read(f, 'utf-8') ?? '');

  const mods = walk(tree, LIB)
    .filter(hasExport)
    .map((f) => './lib/' + f.slice(LIB.length + 1).replace(/\.ts$/, ''))
    .filter((m) => !EXCLUDE.has(m))
    .sort();

  const content = HEADER + mods.map((m) => `export * from '${m}';`).join('\n') + '\n';

  if (tree.read(OUT, 'utf-8') !== content) {
    tree.write(OUT, content);
    return {
      outOfSyncMessage: `${OUT} is out of date. Run \`nx sync\` to update it.`,
    };
  }
  return {};
}
