import type { Tree } from '@nx/devkit';
import { createTreeWithEmptyWorkspace } from '@nx/devkit/testing';
import genPublicApiGenerator from './generator';

const LIB = 'packages/dynamic-forms/internal/src/lib';
const OUT = 'packages/dynamic-forms/internal/src/public_api.ts';

describe('gen-public-api sync generator', () => {
  let tree: Tree;

  beforeEach(() => {
    tree = createTreeWithEmptyWorkspace();
  });

  it('writes a sorted barrel of exporting modules and reports out of sync', () => {
    tree.write(`${LIB}/zeta.ts`, 'export const z = 1;');
    tree.write(`${LIB}/nested/alpha.ts`, 'export type A = string;');
    tree.write(`${LIB}/skipped.spec.ts`, 'export const s = 1;');
    tree.write(`${LIB}/skipped.type-test.ts`, 'export const t = 1;');
    tree.write(`${LIB}/no-exports.ts`, 'const internal = 1;');

    const result = genPublicApiGenerator(tree);

    expect(result).toEqual({ outOfSyncMessage: expect.stringContaining('nx sync') });
    const content = tree.read(OUT, 'utf-8');
    expect(content).toContain('AUTO-GENERATED by the gen-public-api sync generator');
    expect(content?.endsWith("export * from './lib/nested/alpha';\nexport * from './lib/zeta';\n")).toBe(true);
    expect(content).not.toContain('skipped');
    expect(content).not.toContain('no-exports');
  });

  it('is idempotent: a second run reports in sync and changes nothing', () => {
    tree.write(`${LIB}/a.ts`, 'export const a = 1;');
    genPublicApiGenerator(tree);
    const first = tree.read(OUT, 'utf-8');

    const second = genPublicApiGenerator(tree);

    expect(second).toEqual({});
    expect(tree.read(OUT, 'utf-8')).toBe(first);
  });

  it('reports out of sync when the committed barrel drifts', () => {
    tree.write(`${LIB}/a.ts`, 'export const a = 1;');
    genPublicApiGenerator(tree);
    tree.write(OUT, `${tree.read(OUT, 'utf-8') ?? ''}// drift\n`);

    const result = genPublicApiGenerator(tree);

    expect(result).toEqual({ outOfSyncMessage: expect.stringContaining(OUT) });
  });
});
