#!/usr/bin/env node
/**
 * Generates the consumer-facing agent skill under `skills/`.
 *
 * The skill is NOT hand-written. Everything it states about field types,
 * rules, and common mistakes is derived from the same registries the MCP
 * server and the validation CLI use, so the three cannot drift apart.
 *
 * Run `nx run workspace:skills-update` to regenerate; CI runs
 * `skills-check`, which fails if the committed output is stale.
 *
 * Executed by Node's native type stripping, so it must stay free of
 * TypeScript syntax that requires real transformation (enums, namespaces,
 * parameter properties, decorators).
 */

import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { INSTRUCTIONS } from '../packages/dynamic-form-mcp/src/registry/instructions.ts';
import { FIELD_TYPES } from '../packages/dynamic-form-mcp/src/registry/field-types.ts';
import { PATTERNS, COMPLETE_EXAMPLE, MEGA_EXAMPLE } from '../packages/dynamic-form-mcp/src/tools/examples.tool.ts';
import { FIX_SUGGESTIONS } from '../internal/dynamic-forms-validation/reporting/fix-suggestions.ts';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SKILL_DIR = join(ROOT, 'skills', 'dynamic-forms');
const REFERENCES_DIR = join(SKILL_DIR, 'references');

const GENERATED_NOTE = '<!-- Generated by scripts/generate-skills.ts. Do not edit by hand. -->';

async function libraryVersion(): Promise<string> {
  const pkg = JSON.parse(await readFile(join(ROOT, 'packages', 'dynamic-forms', 'package.json'), 'utf-8'));
  return pkg.version;
}

/** The skill entry point. Deliberately short: everything else is progressive disclosure. */
function skillMd(version: string): string {
  return `---
name: ng-forge-dynamic-forms
description: Write and validate @ng-forge/dynamic-forms FormConfig objects for Angular. Use when creating, editing, or debugging dynamic form schemas, field types, validation, conditional logic, or value derivations in a project that depends on @ng-forge/dynamic-forms.
---

${GENERATED_NOTE}

# ng-forge Dynamic Forms

Authoring guidance for \`@ng-forge/dynamic-forms\` FormConfig objects.

This skill documents version **${version}**.

## Before you start

Check what the project actually has installed:

\`\`\`bash
node -p "require('./package.json').dependencies['@ng-forge/dynamic-forms']"
\`\`\`

If it does not match ${version}, say so before generating a config. The rules
below track ${version} and some of them have changed between releases.

## The loop

Do not hand back a config you have not checked. The library ships a validator:

\`\`\`bash
npx @ng-forge/dynamic-forms-cli "path/to/your.form.ts" --ui material
\`\`\`

It reports the exact property that is wrong and how to fix it. Exit code 1
means a config failed, 2 means the invocation was wrong. Run it after writing
or editing any config, and fix what it reports before replying.

If the config is written in TypeScript, \`as const satisfies FormConfig\` plus
a typecheck already catches a large share of mistakes. Use both.

## Non-negotiable rules

These are the mistakes that come up most often. The full set is in
\`references/rules.md\`.

1. **\`options\` goes at field level**, never inside \`props\`.
2. **Hidden fields require \`value\`** and support nothing else: no validators,
   no \`required\`, no \`props\`, no \`col\`.
3. **Containers (page, group, row, array) accept only \`hidden\` logic.** Put
   \`disabled\`, \`required\`, \`readonly\`, and \`derivation\` on child fields.
4. **Container fields take no \`label\`.** Use a \`text\` field inside for headings.
5. **There is no \`hideWhen\`, \`showWhen\`, or \`expressions\` shorthand.** Use
   \`logic: [{ type: 'hidden', condition: {...} }]\`.
6. **Derivations live on the target field**, via \`derivation: '...'\` or
   \`logic: [{ type: 'derivation', expression: '...' }]\`. \`targetField\` no
   longer exists.
7. **Keys are unique within their group scope.** Page, row, and array
   containers do not introduce a scope.
8. **Navigation buttons go inside the page they belong to**, not beside it.

## References

Read these on demand rather than up front:

| File | When to read it |
| ---- | --------------- |
| \`references/rules.md\` | The complete authoring contract, including expression syntax and i18n |
| \`references/field-types.md\` | Which field types exist, their props, and where each may be nested |
| \`references/patterns.md\` | Working configs to adapt: wizards, arrays, conditionals, validation |
| \`references/pitfalls.md\` | Error-to-fix table, the same one the validator emits |

## UI adapters

A config is validated against one adapter: \`material\`, \`bootstrap\`,
\`primeng\`, or \`ionic\`. Field types are shared, but \`props\` differ per
adapter. Check which adapter the project provides before writing \`props\`.
`;
}

function rulesMd(): string {
  return withTableOfContents(`${GENERATED_NOTE}\n\n${INSTRUCTIONS}\n`);
}

/** Escape a value for use inside a markdown table cell. Union types are full of pipes. */
function cell(value: string): string {
  return value.replace(/\|/g, '\\|');
}

/** Files longer than this get a table of contents. */
export const TOC_LINE_THRESHOLD = 100;

/** GitHub-style anchor slug for a heading. */
function anchorFor(heading: string): string {
  return heading
    .toLowerCase()
    .replace(/`/g, '')
    .replace(/[^\w\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-');
}

/**
 * Insert a table of contents into long reference files.
 *
 * Agents preview long files with partial reads (`head -100`), so without a
 * contents list near the top they cannot see what else the file covers.
 * Only `##` headings are listed: deeper levels would bury the shape.
 */
export function withTableOfContents(content: string): string {
  const lines = content.split('\n');
  if (lines.length <= TOC_LINE_THRESHOLD) {
    return content;
  }

  const headings = lines.filter((line) => /^## /.test(line)).map((line) => line.slice(3).trim());

  // A file with one section has nothing worth indexing.
  if (headings.length < 2) {
    return content;
  }

  const toc = ['## Contents', '', ...headings.map((h) => `- [${h}](#${anchorFor(h)})`), ''];

  const titleIndex = lines.findIndex((line) => /^# /.test(line));
  if (titleIndex === -1) {
    return [...toc, ...lines].join('\n');
  }

  // Skip the blank line that follows the title, if there is one.
  const insertAt = lines[titleIndex + 1]?.trim() === '' ? titleIndex + 2 : titleIndex + 1;
  return [...lines.slice(0, insertAt), ...toc, ...lines.slice(insertAt)].join('\n');
}

function fieldTypesMd(): string {
  const lines: string[] = [GENERATED_NOTE, '', '# Field types', ''];

  const categories: Array<['value' | 'container' | 'button' | 'display', string]> = [
    ['value', 'Value fields'],
    ['container', 'Containers'],
    ['button', 'Buttons'],
    ['display', 'Display'],
  ];

  for (const [category, heading] of categories) {
    const types = FIELD_TYPES.filter((f) => f.category === category);
    if (types.length === 0) continue;

    lines.push(`## ${heading}`, '');

    for (const field of types) {
      lines.push(`### \`${field.type}\``, '');
      lines.push(field.description, '');
      if (field.valueType) {
        lines.push(`- Value type: \`${field.valueType}\``);
      }
      lines.push(`- Allowed in: ${field.allowedIn.map((a) => `\`${a}\``).join(', ')}`);
      lines.push(`- Validators supported: ${field.validationSupported ? 'yes' : 'no'}`);
      lines.push('');

      const props = Object.values(field.props ?? {});
      if (props.length > 0) {
        lines.push('| Prop | Type | Required | Default | Description |');
        lines.push('| ---- | ---- | -------- | ------- | ----------- |');
        for (const prop of props) {
          const dflt = prop.default === undefined ? '' : `\`${cell(String(prop.default))}\``;
          lines.push(
            `| \`${cell(prop.name)}\` | \`${cell(prop.type)}\` | ${prop.required ? 'yes' : 'no'} | ${dflt} | ${cell(prop.description ?? '')} |`,
          );
        }
        lines.push('');
      }

      if (field.example) {
        lines.push('```typescript', field.example, '```', '');
      }
    }
  }

  return withTableOfContents(lines.join('\n'));
}

/** Pull fenced TypeScript blocks out of markdown-shaped pattern content. */
function extractTypeScriptBlocks(content: string): string[] {
  const blocks: string[] = [];
  const regex = /```typescript\n([\s\S]*?)```/g;
  let match: RegExpExecArray | null;
  while ((match = regex.exec(content)) !== null) {
    blocks.push(match[1].trim());
  }
  return blocks;
}

/**
 * `complete` and `mega` carry no content in PATTERNS. The examples tool
 * special-cases them ahead of the table and serves these constants instead,
 * so reading PATTERNS alone silently drops the two examples its own
 * description calls the recommended starting points.
 */
const SPECIAL_CASED_EXAMPLES: Record<string, string> = {
  complete: COMPLETE_EXAMPLE,
  mega: MEGA_EXAMPLE,
};

/**
 * Best available code for a pattern: `brief` and `minimal` are raw TypeScript,
 * `full` is markdown wrapping the same config. Patterns with no content in the
 * table fall back to the special-cased constants above.
 */
function patternCode(name: string): string | undefined {
  const pattern = PATTERNS[name];
  for (const depth of ['brief', 'minimal'] as const) {
    const value = pattern[depth].trim();
    if (value.length > 0) {
      return value;
    }
  }

  const fromTable = extractTypeScriptBlocks(pattern.full)[0];
  if (fromTable) {
    return fromTable;
  }

  const special = SPECIAL_CASED_EXAMPLES[name];
  return special ? extractTypeScriptBlocks(special)[0] : undefined;
}

function patternsMd(): string {
  const lines: string[] = [GENERATED_NOTE, '', '# Patterns', ''];
  lines.push('Working configurations to adapt. Every config here is checked against the schema by the test suite.', '');

  const entries = Object.keys(PATTERNS)
    .sort()
    .map((name) => ({ name, code: patternCode(name) }))
    .filter((entry): entry is { name: string; code: string } => entry.code !== undefined);

  lines.push('| Pattern | Description |');
  lines.push('| ------- | ----------- |');
  for (const { name } of entries) {
    lines.push(`| [\`${name}\`](#${name}) | ${cell(PATTERNS[name].description)} |`);
  }
  lines.push('');

  for (const { name, code } of entries) {
    lines.push(`## ${name}`, '', PATTERNS[name].description, '', '```typescript', code, '```', '');
  }

  return lines.join('\n');
}

function pitfallsMd(): string {
  const lines: string[] = [GENERATED_NOTE, '', '# Pitfalls', ''];
  lines.push('The validator emits these fixes directly. They are listed here so a config can be written correctly the first time.', '');
  lines.push('| If you see this property flagged | Do this |');
  lines.push('| -------------------------------- | ------- |');

  for (const key of Object.keys(FIX_SUGGESTIONS).sort()) {
    lines.push(`| \`${cell(key)}\` | ${cell(FIX_SUGGESTIONS[key])} |`);
  }
  lines.push('');

  return lines.join('\n');
}

/** Every file the skill is made of, as [absolute path, contents] pairs. */
export async function buildOutputs(): Promise<Array<[string, string]>> {
  const version = await libraryVersion();
  return [
    [join(SKILL_DIR, 'SKILL.md'), skillMd(version)],
    [join(REFERENCES_DIR, 'rules.md'), rulesMd()],
    [join(REFERENCES_DIR, 'field-types.md'), fieldTypesMd()],
    [join(REFERENCES_DIR, 'patterns.md'), patternsMd()],
    [join(REFERENCES_DIR, 'pitfalls.md'), pitfallsMd()],
  ];
}

const rel = (path: string) => path.replace(`${ROOT}/`, '');

/** Names of generated files whose on-disk contents differ from a fresh render. */
export async function findStaleOutputs(): Promise<string[]> {
  const stale: string[] = [];

  for (const [path, contents] of await buildOutputs()) {
    let onDisk: string | null = null;
    try {
      onDisk = await readFile(path, 'utf-8');
    } catch {
      onDisk = null;
    }
    if (onDisk !== contents) {
      stale.push(rel(path));
    }
  }

  return stale;
}

async function main(): Promise<void> {
  if (process.argv.includes('--check')) {
    const stale = await findStaleOutputs();

    if (stale.length > 0) {
      console.error('[skills-check] FAIL: generated skill files are stale:');
      for (const path of stale) {
        console.error(`  - ${path}`);
      }
      console.error('\nRegenerate with: nx run skills:update');
      process.exitCode = 1;
      return;
    }

    console.log('[skills-check] OK: 5 generated file(s) match their sources.');
    return;
  }

  await rm(SKILL_DIR, { recursive: true, force: true });
  await mkdir(REFERENCES_DIR, { recursive: true });

  for (const [path, contents] of await buildOutputs()) {
    await writeFile(path, contents, 'utf-8');
    console.log(`generated ${rel(path)} (${contents.length} bytes)`);
  }
}

// Only run when invoked directly, so the pure helpers above stay importable
// from tests without generating files as a side effect.
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  await main();
}
