#!/usr/bin/env node
/**
 * Generates the consumer-facing agent skill under `skills/`.
 *
 * The skill is NOT hand-written. Everything it states about field types,
 * rules, and common mistakes is derived from the same registries the MCP
 * server and the validation CLI use, so the three cannot drift apart.
 *
 * Run `nx run skills:update` to regenerate; CI runs `nx run skills:check`,
 * which fails if the committed output is stale.
 *
 * Executed by Node's native type stripping, so it must stay free of
 * TypeScript syntax that requires real transformation (enums, namespaces,
 * parameter properties, decorators).
 */

import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { INSTRUCTIONS } from '../packages/dynamic-form-mcp/src/registry/instructions.ts';
import { FIELD_TYPES } from '../packages/dynamic-form-mcp/src/registry/field-types.ts';
import { UI_ADAPTERS } from '../packages/dynamic-form-mcp/src/registry/ui-adapters.ts';
import { adapterSkillMd, adapterPropsMd, adapterSkillName } from './skill-adapters.ts';
import { PATTERNS } from '../packages/dynamic-form-mcp/src/tools/examples.tool.ts';
import { FIX_SUGGESTIONS } from '../internal/dynamic-forms-validation/reporting/fix-suggestions.ts';
import { RULES, RULE_IDS } from '../internal/dynamic-forms-validation/rules/catalogue.ts';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SKILL_DIR = join(ROOT, 'skills', 'dynamic-forms');
const REFERENCES_DIR = join(SKILL_DIR, 'references');

/**
 * Adapter skills live beside the core one, named after their package.
 *
 * Skills follow package boundaries because that is what a consumer installs:
 * core plus exactly one adapter. A single skill documenting four adapters'
 * props would describe three sets of properties the project does not have,
 * which is the failure mode the `--ui` flag exists to avoid.
 */
const adapterSkillDir = (library: string) => join(ROOT, 'skills', adapterSkillName(library));

const GENERATED_NOTE = '<!-- Generated by scripts/generate-skills.ts. Do not edit by hand. -->';

async function libraryVersion(): Promise<string> {
  const pkg = JSON.parse(await readFile(join(ROOT, 'packages', 'dynamic-forms', 'package.json'), 'utf-8'));
  return pkg.version;
}

/** The skill entry point. Deliberately short: everything else is progressive disclosure. */
function skillMd(version: string): string {
  return `---
name: ng-forge-dynamic-forms
description: Write and validate @ng-forge/dynamic-forms FormConfig objects for Angular. Use when creating, editing, or debugging dynamic form schemas, field types, validation, conditional logic, or value derivations in a project that depends on @ng-forge/dynamic-forms.
---

${GENERATED_NOTE}

# ng-forge Dynamic Forms

Authoring guidance for \`@ng-forge/dynamic-forms\` FormConfig objects.

This skill documents version **${version}**.

## Before you start

Check what the project actually has installed:

\`\`\`bash
node -p "require('@ng-forge/dynamic-forms/package.json').version"
\`\`\`

That reads the resolved package, so it works in a monorepo and when the library
is a dev dependency. Reading \`dependencies\` from the nearest package.json
reports a range like \`^1.2.0\` rather than what is installed, and misses both
cases.

If it does not match ${version}, say so before generating a config. The rules
below track ${version} and some of them have changed between releases.

## The loop

Do not hand back a config you have not checked. The library ships a validator:

\`\`\`bash
npx --yes @ng-forge/dynamic-forms-cli "path/to/your.form.ts" --ui material
\`\`\`

\`--yes\` matters: without it npx prompts before its first install and waits for
an answer that will never come. Requires Node 24 or newer.

It reports the exact property that is wrong and how to fix it. Exit code 1
means a config failed, 2 means the invocation was wrong. Run it after writing
or editing any config, and fix what it reports before replying.

Pass \`--require-config\` when the file is supposed to contain a config: without
it, a file the extractor finds nothing in exits 0, which reads the same as a
clean run.

If the config is written in TypeScript, \`as const satisfies FormConfig\` plus
a typecheck already catches a large share of mistakes. Use both.

## Non-negotiable rules

These are the mistakes that come up most often. The full set is in
\`references/rules.md\`.

1. **\`options\` goes at field level**, never inside \`props\`.
2. **Hidden fields require \`value\`** and support nothing else: no validators,
   no \`required\`, no \`props\`, no \`col\`.
3. **Containers (page, group, row, array) accept only \`hidden\` logic.** Put
   \`disabled\`, \`required\`, \`readonly\`, and \`derivation\` on child fields.
4. **Container fields take no \`label\`.** Use a \`text\` field inside for headings.
5. **There is no \`hideWhen\`, \`showWhen\`, or \`expressions\` shorthand.** Use
   \`logic: [{ type: 'hidden', condition: {...} }]\`.
6. **Derivations live on the target field**, via \`derivation: '...'\` or
   \`logic: [{ type: 'derivation', expression: '...' }]\`. \`targetField\` no
   longer exists.
7. **Keys are unique within their group scope.** Page, row, and array
   containers do not introduce a scope.
8. **Navigation buttons go inside the page they belong to**, not beside it.

## References

Read these on demand rather than up front:

| File | When to read it |
| ---- | --------------- |
| \`references/rules.md\` | The complete authoring contract, including expression syntax and i18n |
| \`references/field-types.md\` | Which field types exist, their props, and where each may be nested |
| \`references/patterns.md\` | Working configs to adapt: wizards, arrays, conditionals, validation |
| \`references/pitfalls.md\` | Error-to-fix table, the same one the validator emits |

## UI adapters

A config is validated against one adapter: \`material\`, \`bootstrap\`,
\`primeng\`, or \`ionic\`. Field types are shared, but \`props\` differ per
adapter, and this skill documents none of them.

Install the skill for the adapter the project uses, which carries its \`props\`:

| Adapter | Skill |
| ------- | ----- |
${UI_ADAPTERS.map((a) => `| \`${a.library}\` | \`ng-forge-dynamic-forms-${a.library}\` |`).join('\n')}

Two adapters cannot both provide the same field type, so a project has one
adapter per field type. Check which one it provides before writing \`props\`.
`;
}

/**
 * The named rules, appended to the authoring instructions.
 *
 * An agent needs the identifier to make sense of a project that has switched one
 * off, and to report accurately why something was accepted. Only semantic rules
 * appear: constraints the type system enforces are not opt-out-able and have no
 * id, because disabling one would ask the validator to accept a config that
 * still would not compile.
 */
function ruleCatalogueMd(): string {
  const lines: string[] = ['## Named rules', ''];

  lines.push(
    'These are conventions checked on top of the schema. A project may switch one',
    'off in `.ng-forge/rules.json`, in which case it reports as a warning rather',
    'than an error, and the identifier below is what appears there.',
    '',
    'Constraints that come from the types — a container having no `label`, an',
    'array-add button needing a `template` — are not in this list and cannot be',
    'disabled: the config would not compile either way.',
    '',
    '| Rule | What it asks | Why |',
    '| ---- | ------------ | --- |',
  );

  for (const id of RULE_IDS) {
    const entry = RULES[id];
    lines.push(`| \`${cell(id)}\` | ${cell(entry.summary)} | ${cell(entry.why)} |`);
  }

  return lines.join('\n');
}

function rulesMd(): string {
  return withTableOfContents(`${GENERATED_NOTE}\n\n${INSTRUCTIONS}\n\n${ruleCatalogueMd()}\n`);
}

/**
 * Escape a value for use inside a markdown table cell. Union types are full of
 * pipes.
 *
 * Backslashes go first. Escaping only the pipe turns a literal `\|` into
 * `\\|`, which renders as an escaped backslash followed by a live pipe and
 * splits the cell. No registry value contains one today, but the registries are
 * hand-edited data.
 */
function cell(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/\|/g, '\\|');
}

/** Files longer than this get a table of contents. */
export const TOC_LINE_THRESHOLD = 100;

/** GitHub-style anchor slug for a heading. */
function anchorFor(heading: string): string {
  return heading
    .toLowerCase()
    .replace(/`/g, '')
    .replace(/[^\w\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-');
}

/**
 * Insert a table of contents into long reference files.
 *
 * Agents preview long files with partial reads (`head -100`), so without a
 * contents list near the top they cannot see what else the file covers.
 * Only `##` headings are listed: deeper levels would bury the shape.
 */
export function withTableOfContents(content: string): string {
  const lines = content.split('\n');
  if (lines.length <= TOC_LINE_THRESHOLD) {
    return content;
  }

  const headings = lines.filter((line) => /^## /.test(line)).map((line) => line.slice(3).trim());

  // A file with one section has nothing worth indexing.
  if (headings.length < 2) {
    return content;
  }

  const toc = ['## Contents', '', ...headings.map((h) => `- [${h}](#${anchorFor(h)})`), ''];

  const titleIndex = lines.findIndex((line) => /^# /.test(line));
  if (titleIndex === -1) {
    return [...toc, ...lines].join('\n');
  }

  // Skip the blank line that follows the title, if there is one.
  const insertAt = lines[titleIndex + 1]?.trim() === '' ? titleIndex + 2 : titleIndex + 1;
  return [...lines.slice(0, insertAt), ...toc, ...lines.slice(insertAt)].join('\n');
}

function fieldTypesMd(): string {
  const lines: string[] = [GENERATED_NOTE, '', '# Field types', ''];

  const categories: Array<['value' | 'container' | 'button' | 'display', string]> = [
    ['value', 'Value fields'],
    ['container', 'Containers'],
    ['button', 'Buttons'],
    ['display', 'Display'],
  ];

  for (const [category, heading] of categories) {
    const types = FIELD_TYPES.filter((f) => f.category === category);
    if (types.length === 0) continue;

    lines.push(`## ${heading}`, '');

    for (const field of types) {
      lines.push(`### \`${field.type}\``, '');
      lines.push(field.description, '');
      if (field.valueType) {
        lines.push(`- Value type: \`${field.valueType}\``);
      }
      lines.push(`- Allowed in: ${field.allowedIn.map((a) => `\`${a}\``).join(', ')}`);
      lines.push(`- Validators supported: ${field.validationSupported ? 'yes' : 'no'}`);
      lines.push('');

      const props = Object.values(field.props ?? {});
      if (props.length > 0) {
        lines.push('| Prop | Type | Required | Default | Description |');
        lines.push('| ---- | ---- | -------- | ------- | ----------- |');
        for (const prop of props) {
          const dflt = prop.default === undefined ? '' : `\`${cell(String(prop.default))}\``;
          lines.push(
            `| \`${cell(prop.name)}\` | \`${cell(prop.type)}\` | ${prop.required ? 'yes' : 'no'} | ${dflt} | ${cell(prop.description ?? '')} |`,
          );
        }
        lines.push('');
      }

      if (field.example) {
        lines.push('```typescript', field.example, '```', '');
      }
    }
  }

  return withTableOfContents(lines.join('\n'));
}

/** Pull fenced TypeScript blocks out of markdown-shaped pattern content. */
function extractTypeScriptBlocks(content: string): string[] {
  const blocks: string[] = [];
  const regex = /```typescript\n([\s\S]*?)```/g;
  let match: RegExpExecArray | null;
  while ((match = regex.exec(content)) !== null) {
    blocks.push(match[1].trim());
  }
  return blocks;
}

/**
 * Best available code for a pattern: `brief` and `minimal` are raw TypeScript,
 * `full` is markdown wrapping the same config. No pattern ships empty, so the
 * undefined branch is a guard against a future one, not a routine case.
 */
function patternCode(name: string): string | undefined {
  const pattern = PATTERNS[name];
  for (const depth of ['brief', 'minimal'] as const) {
    const value = pattern[depth].trim();
    if (value.length > 0) {
      return value;
    }
  }
  return extractTypeScriptBlocks(pattern.full)[0];
}

function patternsMd(): string {
  const lines: string[] = [GENERATED_NOTE, '', '# Patterns', ''];
  lines.push('Working configurations to adapt. Every config here is checked against the schema by the test suite.', '');

  const entries = Object.keys(PATTERNS)
    .sort()
    .map((name) => ({ name, code: patternCode(name) }))
    .filter((entry): entry is { name: string; code: string } => entry.code !== undefined);

  lines.push('| Pattern | Description |');
  lines.push('| ------- | ----------- |');
  for (const { name } of entries) {
    lines.push(`| [\`${name}\`](#${name}) | ${cell(PATTERNS[name].description)} |`);
  }
  lines.push('');

  for (const { name, code } of entries) {
    lines.push(`## ${name}`, '', PATTERNS[name].description, '', '```typescript', code, '```', '');
  }

  return lines.join('\n');
}

function pitfallsMd(): string {
  const lines: string[] = [GENERATED_NOTE, '', '# Pitfalls', ''];
  lines.push('The validator emits these fixes directly. They are listed here so a config can be written correctly the first time.', '');
  lines.push('| If you see this property flagged | Do this |');
  lines.push('| -------------------------------- | ------- |');

  for (const key of Object.keys(FIX_SUGGESTIONS).sort()) {
    lines.push(`| \`${cell(key)}\` | ${cell(FIX_SUGGESTIONS[key])} |`);
  }
  lines.push('');

  return lines.join('\n');
}

/** Every file the skill is made of, as [absolute path, contents] pairs. */
export async function buildOutputs(): Promise<Array<[string, string]>> {
  const version = await libraryVersion();
  return [
    [join(SKILL_DIR, 'SKILL.md'), skillMd(version)],
    [join(REFERENCES_DIR, 'rules.md'), rulesMd()],
    [join(REFERENCES_DIR, 'field-types.md'), fieldTypesMd()],
    [join(REFERENCES_DIR, 'patterns.md'), patternsMd()],
    [join(REFERENCES_DIR, 'pitfalls.md'), pitfallsMd()],
    ...UI_ADAPTERS.flatMap((adapter): Array<[string, string]> => {
      const dir = adapterSkillDir(adapter.library);
      const deps = { generatedNote: GENERATED_NOTE, cell, withTableOfContents };
      return [
        [join(dir, 'SKILL.md'), adapterSkillMd(adapter, version, deps)],
        [join(dir, 'references', 'props.md'), adapterPropsMd(adapter, deps)],
      ];
    }),
  ];
}

/** Every directory the generator owns, so a renamed adapter cannot leave a stale skill behind. */
export function generatedSkillDirs(): string[] {
  return [SKILL_DIR, ...UI_ADAPTERS.map((a) => adapterSkillDir(a.library))];
}

const rel = (path: string) => path.replace(`${ROOT}/`, '');

/** Names of generated files whose on-disk contents differ from a fresh render. */
export async function findStaleOutputs(): Promise<string[]> {
  const stale: string[] = [];

  for (const [path, contents] of await buildOutputs()) {
    let onDisk: string | null = null;
    try {
      onDisk = await readFile(path, 'utf-8');
    } catch {
      onDisk = null;
    }
    if (onDisk !== contents) {
      stale.push(rel(path));
    }
  }

  return stale;
}

async function main(): Promise<void> {
  if (process.argv.includes('--check')) {
    const stale = await findStaleOutputs();

    if (stale.length > 0) {
      console.error('[skills-check] FAIL: generated skill files are stale:');
      for (const path of stale) {
        console.error(`  - ${path}`);
      }
      console.error('\nRegenerate with: nx run skills:update');
      process.exitCode = 1;
      return;
    }

    console.log(`[skills-check] OK: ${(await buildOutputs()).length} generated file(s) match their sources.`);
    return;
  }

  for (const dir of generatedSkillDirs()) {
    await rm(dir, { recursive: true, force: true });
  }

  for (const [path, contents] of await buildOutputs()) {
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, contents, 'utf-8');
    console.log(`generated ${rel(path)} (${contents.length} bytes)`);
  }
}

// Only run when invoked directly, so the pure helpers above stay importable
// from tests without generating files as a side effect.
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  await main();
}
