import { writeFile, mkdir } from 'node:fs/promises';
import { join } from 'node:path';
import { runGenerateAction } from '../../cli/commands/generate.command.js';
import { createTempDir, cleanupDir, fixturePath, readGenerated, readConfigFile, fileExists, typecheckGeneratedForm } from './helpers.js';

let outputDir: string;
let exitSpy: ReturnType<typeof vi.spyOn>;

beforeEach(async () => {
  outputDir = await createTempDir();
  exitSpy = vi.spyOn(process, 'exit').mockImplementation((() => {
    // no-op: prevent process from actually exiting
  }) as never);
});

afterEach(async () => {
  await cleanupDir(outputDir);
  exitSpy.mockRestore();
});

function generate(fixture: string, overrides: Record<string, unknown> = {}) {
  return runGenerateAction({
    spec: fixturePath(fixture),
    output: outputDir,
    interactive: 'none',
    ...overrides,
  } as Parameters<typeof runGenerateAction>[0]);
}

// ─── A. Basic Pipeline ───────────────────────────────────────────────

describe('Basic Pipeline', () => {
  it('should generate form config, interface, and barrel files', async () => {
    await generate('basic-post.yaml');

    const form = await readGenerated(outputDir, 'forms', 'create-user.form.ts');
    expect(form).toContain("key: 'name'");
    expect(form).toContain("type: 'input'");
    expect(form).toContain('as const satisfies FormConfig');
    expect(form).toContain('// @generated by @ng-forge/openapi-generator');

    const types = await readGenerated(outputDir, 'types', 'create-user.types.ts');
    expect(types).toContain('export interface CreateUserFormValue');

    const formBarrel = await readGenerated(outputDir, 'forms', 'index.ts');
    expect(formBarrel).toContain("from './create-user.form'");
    expect(formBarrel).not.toContain('.js');

    const typeBarrel = await readGenerated(outputDir, 'types', 'index.ts');
    expect(typeBarrel).toContain("from './create-user.types'");
    expect(typeBarrel).not.toContain('.js');
  });

  it('should generate correct required/optional interface properties', async () => {
    await generate('basic-post.yaml');

    const types = await readGenerated(outputDir, 'types', 'create-user.types.ts');
    expect(types).toContain('name: string');
    expect(types).toContain('age?: number');
    expect(types).toContain('active?: boolean');
  });

  it('should save config file with endpoints and decisions', async () => {
    await generate('basic-post.yaml');

    const config = await readConfigFile(outputDir);
    expect(config['endpoints']).toEqual(['POST:/users']);
    expect(config['decisions']).toBeDefined();
  });

  it('should omit barrelExtension from config when using the default', async () => {
    await generate('basic-post.yaml');

    const config = await readConfigFile(outputDir);
    // Default (empty) state is representable as "field absent" so users can tell
    // apart "never configured" from "explicitly empty".
    expect(config['barrelExtension']).toBeUndefined();
  });

  it('should emit .js suffixes and persist barrelExtension when requested', async () => {
    await generate('basic-post.yaml', { barrelExtension: '.js' });

    const formBarrel = await readGenerated(outputDir, 'forms', 'index.ts');
    expect(formBarrel).toContain("from './create-user.form.js'");

    const config = await readConfigFile(outputDir);
    expect(config['barrelExtension']).toBe('.js');
  });

  it('should honor saved barrelExtension on re-run without the flag', async () => {
    // First run: opt into .js and persist.
    await generate('basic-post.yaml', { barrelExtension: '.js' });
    // Second run: no flag — must reuse the saved value, not fall back to default.
    await generate('basic-post.yaml');

    const formBarrel = await readGenerated(outputDir, 'forms', 'index.ts');
    expect(formBarrel).toContain("from './create-user.form.js'");

    const config = await readConfigFile(outputDir);
    expect(config['barrelExtension']).toBe('.js');
  });

  it('should clear saved barrelExtension when explicitly set to empty', async () => {
    // Prime a persisted .js value.
    await generate('basic-post.yaml', { barrelExtension: '.js' });
    // Explicit reset.
    await generate('basic-post.yaml', { barrelExtension: '' });

    const formBarrel = await readGenerated(outputDir, 'forms', 'index.ts');
    expect(formBarrel).toContain("from './create-user.form'");
    expect(formBarrel).not.toContain('.js');

    const config = await readConfigFile(outputDir);
    expect(config['barrelExtension']).toBeUndefined();
  });

  it('should produce a form file that compiles against the published types', async () => {
    await generate('basic-post.yaml');

    const formPath = join(outputDir, 'forms', 'create-user.form.ts');
    const diagnostics = typecheckGeneratedForm(formPath);

    expect(diagnostics, `Generated form should type-check cleanly. Errors:\n${diagnostics.join('\n')}`).toEqual([]);
  }, 30_000); // tsc program creation + type-check is slow in CI
});

// ─── B. Validators ───────────────────────────────────────────────────

describe('Validators', () => {
  it('should map all OpenAPI validators to form validators', async () => {
    await generate('validators.yaml');

    const form = await readGenerated(outputDir, 'forms', 'create-contact.form.ts');
    expect(form).toContain("type: 'required'");
    expect(form).toContain("type: 'email'");
    expect(form).toContain("type: 'minLength', value: 3");
    expect(form).toContain("type: 'maxLength', value: 20");
    expect(form).toContain("type: 'pattern'");
    expect(form).toContain("type: 'min', value: 0");
    expect(form).toContain("type: 'max', value: 100");
  });
});

// ─── C. Enums ────────────────────────────────────────────────────────

describe('Enums', () => {
  it('should map string enum to select with humanized labels', async () => {
    await generate('enums.yaml');

    const form = await readGenerated(outputDir, 'forms', 'create-order.form.ts');
    expect(form).toContain("key: 'status'");
    expect(form).toContain("type: 'select'");
    expect(form).toContain("label: 'Pending'");
    expect(form).toContain("value: 'pending'");
  });

  it('should map array with enum items to multi-checkbox', async () => {
    await generate('enums.yaml');

    const form = await readGenerated(outputDir, 'forms', 'create-order.form.ts');
    expect(form).toContain("key: 'tags'");
    expect(form).toContain("type: 'multi-checkbox'");
  });
});

// ─── D. Nested Objects ───────────────────────────────────────────────

describe('Nested Objects', () => {
  it('should map object properties to group fields with children', async () => {
    await generate('nested-objects.yaml');

    const form = await readGenerated(outputDir, 'forms', 'create-profile.form.ts');
    expect(form).toContain("key: 'address'");
    expect(form).toContain("type: 'group'");
    expect(form).toContain("key: 'street'");
    expect(form).toContain("key: 'city'");
    expect(form).toContain("key: 'zip'");
  });
});

// ─── E. Arrays ───────────────────────────────────────────────────────

describe('Arrays', () => {
  it('should map array of objects to array field with template', async () => {
    await generate('arrays.yaml');

    const form = await readGenerated(outputDir, 'forms', 'create-team.form.ts');
    expect(form).toContain("key: 'members'");
    expect(form).toContain("type: 'array'");
    expect(form).toContain('template');
    expect(form).toContain("key: 'firstName'");
    expect(form).toContain("key: 'role'");
    expect(form).toContain('addButton');
    expect(form).toContain('removeButton');
  });

  it('should map array of primitives to array field with single template', async () => {
    await generate('arrays.yaml');

    const form = await readGenerated(outputDir, 'forms', 'create-team.form.ts');
    expect(form).toContain("key: 'scores'");
  });
});

// ─── F. allOf ────────────────────────────────────────────────────────

describe('allOf', () => {
  it('should merge allOf schemas in form config', async () => {
    await generate('allof-merge.yaml');

    const form = await readGenerated(outputDir, 'forms', 'create-employee.form.ts');
    expect(form).toContain("key: 'id'");
    expect(form).toContain("key: 'name'");
    expect(form).toContain("key: 'department'");
    expect(form).toContain("key: 'salary'");
  });

  it('should merge allOf schemas in interface with correct optionality', async () => {
    await generate('allof-merge.yaml');

    const types = await readGenerated(outputDir, 'types', 'create-employee.types.ts');
    expect(types).toContain('name: string');
    expect(types).toContain('salary: number');
    expect(types).toContain('id?: number');
    expect(types).toContain('department?: string');
  });
});

// ─── G. oneOf + Discriminator ────────────────────────────────────────

describe('oneOf + Discriminator', () => {
  it('should generate radio field for discriminator property', async () => {
    await generate('oneof-discriminator.yaml');

    const form = await readGenerated(outputDir, 'forms', 'create-payment.form.ts');
    expect(form).toContain("key: 'paymentMethod'");
    expect(form).toContain("type: 'radio'");
    expect(form).toContain("'credit_card'");
    expect(form).toContain("'bank_transfer'");
  });

  it('should generate conditional groups with logic blocks', async () => {
    await generate('oneof-discriminator.yaml');

    const form = await readGenerated(outputDir, 'forms', 'create-payment.form.ts');
    expect(form).toContain("type: 'group'");
    expect(form).toContain('logic');
    expect(form).toContain("type: 'hidden'");
    expect(form).toContain("key: 'cardNumber'");
    expect(form).toContain("key: 'accountNumber'");
  });

  it('should generate interface with all variant properties', async () => {
    await generate('oneof-discriminator.yaml');

    const types = await readGenerated(outputDir, 'types', 'create-payment.types.ts');
    expect(types).toContain('paymentMethod');
    expect(types).toContain('cardNumber');
    expect(types).toContain('accountNumber');
  });
});

// ─── H. GET Endpoints ────────────────────────────────────────────────

describe('GET Endpoints', () => {
  it('should generate editable fields for GET by default', async () => {
    await generate('get-endpoints.yaml', { endpoints: 'GET:/settings' });

    const form = await readGenerated(outputDir, 'forms', 'get-settings.form.ts');
    expect(form).not.toContain('disabled: true');
  });

  it('should generate disabled fields for GET with --read-only', async () => {
    await generate('get-endpoints.yaml', { endpoints: 'GET:/settings', readOnly: true });

    const form = await readGenerated(outputDir, 'forms', 'get-settings.form.ts');
    expect(form).toContain('disabled: true');
  });

  it('should skip GET endpoint with top-level array response', async () => {
    await generate('get-endpoints.yaml', { endpoints: 'GET:/items' });

    // Should not generate form files (only empty barrels)
    const exists = await fileExists(join(outputDir, 'forms', 'list-items.form.ts'));
    expect(exists).toBe(false);
  });
});

// ─── I. Config Persistence ───────────────────────────────────────────

describe('Config Persistence', () => {
  it('should produce unchanged files on re-run with saved config', async () => {
    await generate('basic-post.yaml');
    const firstRun = await readGenerated(outputDir, 'forms', 'create-user.form.ts');

    // Re-run — config file already exists
    await generate('basic-post.yaml');
    const secondRun = await readGenerated(outputDir, 'forms', 'create-user.form.ts');

    expect(firstRun).toBe(secondRun);
  });

  it('should respect saved endpoint selections on re-run', async () => {
    // First run with specific endpoint filter
    await generate('multi-endpoint.yaml', { endpoints: 'POST:/pets' });

    const config = await readConfigFile(outputDir);
    expect(config['endpoints']).toEqual(['POST:/pets']);

    // Second run without --endpoints flag — should use saved config
    await generate('multi-endpoint.yaml');

    // Should still only have the one form from the saved selection
    const exists = await fileExists(join(outputDir, 'forms', 'create-pet.form.ts'));
    expect(exists).toBe(true);
  });
});

// ─── J. CLI Flags ────────────────────────────────────────────────────

describe('CLI Flags', () => {
  it('should not write files with --dry-run', async () => {
    await generate('basic-post.yaml', { dryRun: true });

    const formsExist = await fileExists(join(outputDir, 'forms'));
    expect(formsExist).toBe(false);
  });

  it('should preserve existing files with --skip-existing', async () => {
    // Pre-create a file
    await mkdir(join(outputDir, 'forms'), { recursive: true });
    await writeFile(join(outputDir, 'forms', 'create-user.form.ts'), 'CUSTOM CONTENT');

    await generate('basic-post.yaml', { skipExisting: true });

    const content = await readGenerated(outputDir, 'forms', 'create-user.form.ts');
    expect(content).toBe('CUSTOM CONTENT');
  });

  it('should filter to selected endpoints only with --endpoints', async () => {
    await generate('multi-endpoint.yaml', { endpoints: 'POST:/pets' });

    const createPet = await fileExists(join(outputDir, 'forms', 'create-pet.form.ts'));
    const updatePet = await fileExists(join(outputDir, 'forms', 'update-pet.form.ts'));

    expect(createPet).toBe(true);
    expect(updatePet).toBe(false);
  });
});

// ─── K. Name Heuristics ──────────────────────────────────────────────

describe('Name Heuristics', () => {
  it('should resolve description/body fields to textarea', async () => {
    await generate('name-heuristics.yaml');

    const form = await readGenerated(outputDir, 'forms', 'create-article.form.ts');

    // description and body should be textarea (name heuristic)
    const descIdx = form.indexOf("key: 'description'");
    const bodyIdx = form.indexOf("key: 'body'");
    const descSection = form.slice(descIdx, descIdx + 200);
    const bodySection = form.slice(bodyIdx, bodyIdx + 200);

    expect(descSection).toContain("type: 'textarea'");
    expect(bodySection).toContain("type: 'textarea'");

    // title should remain input
    const titleIdx = form.indexOf("key: 'title'");
    const titleSection = form.slice(titleIdx, titleIdx + 200);
    expect(titleSection).toContain("type: 'input'");
  });

  it('should resolve phone field to input with type tel', async () => {
    await generate('name-heuristics.yaml');

    const form = await readGenerated(outputDir, 'forms', 'create-article.form.ts');

    const phoneIdx = form.indexOf("key: 'phone'");
    const phoneSection = form.slice(phoneIdx, phoneIdx + 200);
    expect(phoneSection).toContain("type: 'input'");
    expect(phoneSection).toContain('type: "tel"');
  });
});

// ─── L. Custom Extensions ────────────────────────────────────────────

describe('Custom Extensions', () => {
  it('should use x-ng-forge-type to override field type', async () => {
    await generate('custom-extensions.yaml');

    const form = await readGenerated(outputDir, 'forms', 'create-custom.form.ts');

    const ratingIdx = form.indexOf("key: 'rating'");
    const ratingSection = form.slice(ratingIdx, ratingIdx + 200);
    expect(ratingSection).toContain("type: 'slider'");
  });

  it('should use x-enum-labels for custom option labels', async () => {
    await generate('custom-extensions.yaml');

    const form = await readGenerated(outputDir, 'forms', 'create-custom.form.ts');
    expect(form).toContain("label: 'Low Priority'");
    expect(form).toContain("label: 'Medium Priority'");
    expect(form).toContain("label: 'High Priority'");
  });
});

// ─── M. Edge Cases ───────────────────────────────────────────────────

describe('Edge Cases', () => {
  it('should exit with code 1 for spec with no endpoints', async () => {
    // Write a minimal spec with no paths
    const emptySpec = join(outputDir, 'empty.yaml');
    await writeFile(emptySpec, `openapi: '3.0.3'\ninfo:\n  title: Test\n  version: '1.0.0'\npaths: {}`);

    await runGenerateAction({
      spec: emptySpec,
      output: outputDir,
      interactive: 'none',
    } as Parameters<typeof runGenerateAction>[0]);

    expect(exitSpy).toHaveBeenCalledWith(1);
  });

  it('should generate correctly named files for multiple endpoints', async () => {
    await generate('multi-endpoint.yaml');

    const createPet = await fileExists(join(outputDir, 'forms', 'create-pet.form.ts'));
    const updatePet = await fileExists(join(outputDir, 'forms', 'update-pet.form.ts'));
    const getPet = await fileExists(join(outputDir, 'forms', 'get-pet.form.ts'));

    expect(createPet).toBe(true);
    expect(updatePet).toBe(true);
    expect(getPet).toBe(true);
  });
});

// ─── N. Nullable Values (issue #341) ─────────────────────────────────

describe('Nullable values', () => {
  it('should emit nullable:true + value:null for OpenAPI 3.0 nullable fields', async () => {
    await generate('nullable-values.yaml');

    const form = await readGenerated(outputDir, 'forms', 'create-user.form.ts');
    // middleName has nullable + default:null
    expect(form).toContain("key: 'middleName'");
    expect(form).toMatch(/value:\s*null,\s*\n\s*nullable:\s*true/);
    // nickname has nullable without default → just nullable
    expect(form).toContain("key: 'nickname'");
    // age has nullable:true + default:null on a numeric field
    expect(form).toContain("key: 'age'");
    expect(form).toContain('type: "number"');
  });

  it('should emit union types with null in generated interfaces', async () => {
    await generate('nullable-values.yaml');

    const types = await readGenerated(outputDir, 'types', 'create-user.types.ts');
    expect(types).toContain('name: string');
    expect(types).toContain('middleName?: string | null');
    expect(types).toContain('age?: number | null');
  });

  it('should produce a form file that compiles against the published types (regression for #341)', async () => {
    await generate('nullable-values.yaml');

    const formPath = join(outputDir, 'forms', 'create-user.form.ts');
    const diagnostics = typecheckGeneratedForm(formPath);

    expect(diagnostics, `Generated form should type-check cleanly. Errors:\n${diagnostics.join('\n')}`).toEqual([]);
  }, 30_000); // tsc program creation + type-check is slow in CI

  it('should silently drop nullable:true for field types that do not support it', async () => {
    await generate('nullable-edge-cases.yaml');

    const form = await readGenerated(outputDir, 'forms', 'create-entity.form.ts');
    // Nullable on value fields (select, datepicker, input) — emitted
    expect(form).toMatch(/key: 'status',[\s\S]+?type: 'select',[\s\S]+?nullable: true/);
    expect(form).toMatch(/key: 'startDate',[\s\S]+?type: 'datepicker',[\s\S]+?nullable: true/);
    // Nullable on container/checked — NOT emitted
    // (find the 'subscribed' block: checkbox field; it should NOT have `nullable: true` on that block)
    const subscribedBlock = form.substring(form.indexOf("key: 'subscribed'"));
    expect(subscribedBlock.split('},')[0]).not.toContain('nullable: true');
    const addressBlock = form.substring(form.indexOf("key: 'address'"), form.indexOf("key: 'tags'"));
    expect(addressBlock).not.toContain('nullable: true');
  });

  it('should propagate nullable onto array primitive templates', async () => {
    await generate('nullable-edge-cases.yaml');

    const form = await readGenerated(outputDir, 'forms', 'create-entity.form.ts');
    // scores: array of nullable integers → template has nullable:true, outer array does not
    const scoresBlock = form.substring(form.indexOf("key: 'scores'"), form.indexOf("key: 'subscribed'"));
    expect(scoresBlock).toMatch(/template:\s*\{[\s\S]+?nullable: true/);
  });
});
