/**
 * Generate a barrel (index.ts) file that re-exports all generated form configs.
 */
export function generateBarrel(fileNames: string[]): string {
  if (fileNames.length === 0) {
    return '';
  }

  const lines = [
    '// @generated by @ng-forge/openapi-generator — DO NOT EDIT',
    ...fileNames.map((name) => {
      const moduleName = name.replace(/\.ts$/, '.js');
      return `export * from './${moduleName}';`;
    }),
  ];

  lines.push('');
  return lines.join('\n');
}
