export interface BarrelOptions {
  extension?: string;
}

/**
 * Generate a barrel (index.ts) file that re-exports all generated form configs.
 */
export function generateBarrel(fileNames: string[], options?: BarrelOptions): string {
  if (fileNames.length === 0) {
    return '';
  }

  const ext = options?.extension ?? '';

  const lines = [
    '// @generated by @ng-forge/openapi-generator ',
    ...fileNames.map((name) => {
      const moduleName = name.replace(/\.ts$/, ext);
      return `export * from './${moduleName}';`;
    }),
  ];

  lines.push('');
  return lines.join('\n');
}
