import { generateBarrel } from './barrel-generator';

describe('generateBarrel', () => {
  it('should generate barrel with multiple files', () => {
    const result = generateBarrel(['create-pet.form.ts', 'update-pet.form.ts']);

    expect(result).toContain("export * from './create-pet.form';");
    expect(result).toContain("export * from './update-pet.form';");
  });

  it('should strip .ts extension by default', () => {
    const result = generateBarrel(['my-form.ts']);

    expect(result).toContain("export * from './my-form';");
    expect(result).not.toContain('.ts');
  });

  it('should end with a trailing newline', () => {
    const result = generateBarrel(['a.ts']);

    expect(result).toMatch(/\n$/);
  });

  it('should handle empty array', () => {
    const result = generateBarrel([]);

    expect(result).toBe('');
  });

  it('should include @generated header', () => {
    const result = generateBarrel(['form.ts']);

    expect(result).toMatch(/^\/\/ @generated by @ng-forge\/openapi-generator \n/);
  });

  it('should emit .js extension when provided (Node ESM / nodenext)', () => {
    const result = generateBarrel(['create-pet.form.ts'], { extension: '.js' });

    expect(result).toContain("export * from './create-pet.form.js';");
  });

  it('should default to no extension when no options provided', () => {
    const result = generateBarrel(['create-pet.form.ts']);

    expect(result).toContain("export * from './create-pet.form';");
    expect(result).not.toContain('.js');
  });
});
