import type { FieldConfig } from '../mapper/schema-to-fields.js';
import { toFormConfigName } from '../utils/naming.js';

export interface FormConfigGeneratorOptions {
  method: string;
  path: string;
  operationId?: string;
}

export function generateFormConfig(fields: FieldConfig[], options: FormConfigGeneratorOptions): string {
  const configName = toFormConfigName(options.method, options.path, options.operationId);
  const indent = '  ';

  const lines: string[] = [
    `// @generated by @ng-forge/openapi-generator `,
    `import type { FormConfig } from '@ng-forge/dynamic-forms';`,
    ``,
    `export const ${configName} = {`,
    `${indent}fields: [`,
  ];

  for (const field of fields) {
    lines.push(...generateFieldLines(field, indent + indent));
  }

  lines.push(`${indent}],`);
  lines.push(`} as const satisfies FormConfig;`);
  lines.push(``);

  return lines.join('\n');
}

function generateFieldLines(field: FieldConfig, indent: string): string[] {
  const lines: string[] = [];
  lines.push(`${indent}{`);
  lines.push(`${indent}  key: '${escapeString(field.key)}',`);
  lines.push(`${indent}  type: '${escapeString(field.type)}',`);
  if (field.label !== undefined) {
    lines.push(`${indent}  label: '${escapeString(field.label)}',`);
  }

  if (field.value !== undefined) {
    lines.push(`${indent}  value: ${JSON.stringify(field.value)},`);
  }

  if (field.nullable) {
    lines.push(`${indent}  nullable: true,`);
  }

  if (field.placeholder) {
    lines.push(`${indent}  placeholder: '${escapeString(field.placeholder)}',`);
  }

  if (field.props && Object.keys(field.props).length > 0) {
    lines.push(`${indent}  props: ${formatObject(field.props, indent + '  ')},`);
  }

  if (field.options && field.options.length > 0) {
    lines.push(`${indent}  options: [`);
    for (const opt of field.options) {
      lines.push(`${indent}    { label: '${escapeString(opt.label)}', value: '${escapeString(opt.value)}' },`);
    }
    lines.push(`${indent}  ],`);
  }

  if (field.validators && field.validators.length > 0) {
    lines.push(`${indent}  validators: [`);
    for (const v of field.validators) {
      if (v.value !== undefined) {
        lines.push(`${indent}    { type: '${escapeString(v.type)}', value: ${JSON.stringify(v.value)} },`);
      } else {
        lines.push(`${indent}    { type: '${escapeString(v.type)}' },`);
      }
    }
    lines.push(`${indent}  ],`);
  }

  if (field.disabled) {
    lines.push(`${indent}  disabled: true,`);
  }

  if (field.fields && field.fields.length > 0) {
    lines.push(`${indent}  fields: [`);
    for (const child of field.fields) {
      lines.push(...generateFieldLines(child, indent + '    '));
    }
    lines.push(`${indent}  ],`);
  }

  if (field.template !== undefined) {
    if (Array.isArray(field.template)) {
      // Object array: template is array of fields
      lines.push(`${indent}  template: [`);
      for (const child of field.template) {
        lines.push(...generateFieldLines(child, indent + '    '));
      }
      lines.push(`${indent}  ],`);
    } else {
      // Primitive array: template is a single field object
      // Reuse generateFieldLines and prefix first line with 'template: '
      const tplLines = generateFieldLines(field.template, indent + '  ');
      tplLines[0] = `${indent}  template: ${tplLines[0].trimStart()}`;
      lines.push(...tplLines);
    }
  }

  if (field.addButton !== undefined) {
    if (field.addButton === false) {
      lines.push(`${indent}  addButton: false,`);
    } else {
      if (field.addButton.props && Object.keys(field.addButton.props).length > 0) {
        lines.push(
          `${indent}  addButton: { label: '${escapeString(field.addButton.label)}', props: ${formatObject(field.addButton.props, indent + '  ')} },`,
        );
      } else {
        lines.push(`${indent}  addButton: { label: '${escapeString(field.addButton.label)}' },`);
      }
    }
  }

  if (field.removeButton !== undefined) {
    if (field.removeButton === false) {
      lines.push(`${indent}  removeButton: false,`);
    } else {
      if (field.removeButton.props && Object.keys(field.removeButton.props).length > 0) {
        lines.push(
          `${indent}  removeButton: { label: '${escapeString(field.removeButton.label)}', props: ${formatObject(field.removeButton.props, indent + '  ')} },`,
        );
      } else {
        lines.push(`${indent}  removeButton: { label: '${escapeString(field.removeButton.label)}' },`);
      }
    }
  }

  if (field.logic && field.logic.length > 0) {
    lines.push(`${indent}  logic: [`);
    for (const logic of field.logic) {
      lines.push(`${indent}    {`);
      lines.push(`${indent}      type: '${escapeString(logic.type)}',`);
      lines.push(`${indent}      condition: ${formatObject(logic.condition as Record<string, unknown>, indent + '      ')},`);
      lines.push(`${indent}    },`);
    }
    lines.push(`${indent}  ],`);
  }

  lines.push(`${indent}},`);
  return lines;
}

function escapeString(str: string): string {
  return str.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

function isValidIdentifier(key: string): boolean {
  return /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(key);
}

function formatKey(key: string): string {
  return isValidIdentifier(key) ? key : `'${escapeString(key)}'`;
}

function formatObject(obj: Record<string, unknown>, indent: string): string {
  const entries = Object.entries(obj);
  if (entries.length === 1) {
    const [key, value] = entries[0];
    return `{ ${formatKey(key)}: ${JSON.stringify(value)} }`;
  }
  const lines = entries.map(([key, value]) => `${indent}  ${formatKey(key)}: ${JSON.stringify(value)},`);
  return `{\n${lines.join('\n')}\n${indent}}`;
}
