import type { FieldConfig } from '../mapper/schema-to-fields';
import { generateFormConfig } from './form-config-generator';
import type { FormConfigGeneratorOptions } from './form-config-generator';

const defaultOptions: FormConfigGeneratorOptions = {
  method: 'POST',
  path: '/pets',
  operationId: 'createPet',
};

describe('generateFormConfig', () => {
  it('should generate a simple form config with basic fields', () => {
    const fields: FieldConfig[] = [
      { key: 'name', type: 'text', label: 'Name' },
      { key: 'age', type: 'number', label: 'Age' },
    ];

    const result = generateFormConfig(fields, defaultOptions);

    expect(result).toContain('export const createPetFormConfig = {');
    expect(result).toContain("key: 'name'");
    expect(result).toContain("type: 'text'");
    expect(result).toContain("key: 'age'");
    expect(result).toContain("type: 'number'");
  });

  it('should include as const satisfies FormConfig', () => {
    const result = generateFormConfig([], defaultOptions);

    expect(result).toContain('} as const satisfies FormConfig;');
  });

  it('should include correct import statement', () => {
    const result = generateFormConfig([], defaultOptions);

    expect(result).toContain("import type { FormConfig } from '@ng-forge/dynamic-forms';");
  });

  it('should generate fields with props', () => {
    const fields: FieldConfig[] = [{ key: 'bio', type: 'textarea', label: 'Bio', props: { rows: 5 } }];

    const result = generateFormConfig(fields, defaultOptions);

    expect(result).toContain('props: { rows: 5 }');
  });

  it('should generate fields with multi-value props', () => {
    const fields: FieldConfig[] = [{ key: 'bio', type: 'textarea', label: 'Bio', props: { rows: 5, cols: 40 } }];

    const result = generateFormConfig(fields, defaultOptions);

    expect(result).toContain('rows: 5,');
    expect(result).toContain('cols: 40,');
  });

  it('should generate fields with options', () => {
    const fields: FieldConfig[] = [
      {
        key: 'status',
        type: 'select',
        label: 'Status',
        options: [
          { label: 'Active', value: 'active' },
          { label: 'Inactive', value: 'inactive' },
        ],
      },
    ];

    const result = generateFormConfig(fields, defaultOptions);

    expect(result).toContain("{ label: 'Active', value: 'active' }");
    expect(result).toContain("{ label: 'Inactive', value: 'inactive' }");
  });

  it('should generate fields with validators', () => {
    const fields: FieldConfig[] = [
      {
        key: 'email',
        type: 'text',
        label: 'Email',
        validators: [{ type: 'required' }, { type: 'maxLength', value: 100 }],
      },
    ];

    const result = generateFormConfig(fields, defaultOptions);

    expect(result).toContain('validators: [');
    expect(result).toContain("{ type: 'required' }");
    expect(result).toContain("{ type: 'maxLength', value: 100 }");
  });

  it('should generate disabled fields', () => {
    const fields: FieldConfig[] = [{ key: 'id', type: 'number', label: 'Id', disabled: true }];

    const result = generateFormConfig(fields, defaultOptions);

    expect(result).toContain('disabled: true');
  });

  it('should generate nested fields for groups', () => {
    const fields: FieldConfig[] = [
      {
        key: 'address',
        type: 'group',
        label: 'Address',
        fields: [
          { key: 'street', type: 'text', label: 'Street' },
          { key: 'city', type: 'text', label: 'City' },
        ],
      },
    ];

    const result = generateFormConfig(fields, defaultOptions);

    expect(result).toContain("key: 'address'");
    expect(result).toContain("type: 'group'");
    expect(result).toContain("key: 'street'");
    expect(result).toContain("key: 'city'");
    expect(result).toContain('fields: [');
  });

  it('should escape single quotes in labels', () => {
    const fields: FieldConfig[] = [{ key: 'name', type: 'text', label: "Pet's Name" }];

    const result = generateFormConfig(fields, defaultOptions);

    expect(result).toContain("label: 'Pet\\'s Name'");
  });

  it('should use path-based name when operationId is not provided', () => {
    const options: FormConfigGeneratorOptions = {
      method: 'POST',
      path: '/pets',
    };

    const result = generateFormConfig([], options);

    expect(result).toContain('export const postPetsFormConfig = {');
  });

  it('should quote non-identifier keys in props', () => {
    const fields: FieldConfig[] = [{ key: 'field', type: 'input', label: 'Field', props: { 'aria-label': 'test' } }];

    const result = generateFormConfig(fields, defaultOptions);

    expect(result).toContain('\'aria-label\': "test"');
  });

  it('should include @generated header', () => {
    const result = generateFormConfig([], defaultOptions);

    expect(result).toMatch(/^\/\/ @generated by @ng-forge\/openapi-generator \n/);
  });

  it('should render value property when present', () => {
    const fields: FieldConfig[] = [{ key: 'name', type: 'text', label: 'Name', value: 'default-name' }];

    const result = generateFormConfig(fields, defaultOptions);

    expect(result).toContain('value: "default-name"');
  });

  it('should render numeric value', () => {
    const fields: FieldConfig[] = [{ key: 'count', type: 'number', label: 'Count', value: 42 }];

    const result = generateFormConfig(fields, defaultOptions);

    expect(result).toContain('value: 42');
  });

  it('should render placeholder when present', () => {
    const fields: FieldConfig[] = [{ key: 'bio', type: 'textarea', label: 'Bio', placeholder: 'Enter your bio' }];

    const result = generateFormConfig(fields, defaultOptions);

    expect(result).toContain("placeholder: 'Enter your bio'");
  });

  it('should render nullable: true when field is nullable', () => {
    const fields: FieldConfig[] = [{ key: 'note', type: 'input', label: 'Note', nullable: true }];

    const result = generateFormConfig(fields, defaultOptions);

    expect(result).toContain('nullable: true');
  });

  it('should render nullable together with null value', () => {
    const fields: FieldConfig[] = [{ key: 'note', type: 'input', label: 'Note', nullable: true, value: null }];

    const result = generateFormConfig(fields, defaultOptions);

    expect(result).toContain('nullable: true');
    expect(result).toContain('value: null');
  });

  it('should omit nullable line when field is not nullable', () => {
    const fields: FieldConfig[] = [{ key: 'note', type: 'input', label: 'Note' }];

    const result = generateFormConfig(fields, defaultOptions);

    expect(result).not.toContain('nullable');
  });

  it('should render logic blocks when present', () => {
    const fields: FieldConfig[] = [
      {
        key: 'dogVariant',
        type: 'group',
        label: 'Dog',
        fields: [{ key: 'breed', type: 'input', label: 'Breed' }],
        logic: [
          {
            type: 'hidden',
            condition: {
              type: 'fieldValue',
              fieldPath: 'petType',
              operator: 'notEquals',
              value: 'dog',
            },
          },
        ],
      },
    ];

    const result = generateFormConfig(fields, defaultOptions);

    expect(result).toContain("type: 'hidden'");
    expect(result).toContain('condition: {');
    expect(result).toContain('type: "fieldValue"');
    expect(result).toContain('fieldPath: "petType"');
    expect(result).toContain('operator: "notEquals"');
    expect(result).toContain('value: "dog"');
    expect(result).toContain('logic: [');
  });

  it('should not quote valid identifier keys in props', () => {
    const fields: FieldConfig[] = [{ key: 'field', type: 'input', label: 'Field', props: { rows: 5 } }];

    const result = generateFormConfig(fields, defaultOptions);

    expect(result).toContain('rows: 5');
    expect(result).not.toContain("'rows'");
  });
});

describe('array template rendering', () => {
  const defaultOptions: FormConfigGeneratorOptions = { method: 'POST', path: '/items', operationId: 'createItem' };

  it('should render single template for primitive arrays', () => {
    const fields: FieldConfig[] = [
      {
        key: 'tags',
        type: 'array',
        label: 'Tags',
        template: { key: 'value', type: 'input', label: 'Tag', props: { type: 'text' } },
        addButton: { label: 'Add Tag' },
        removeButton: { label: 'Remove' },
      },
    ];

    const result = generateFormConfig(fields, defaultOptions);

    expect(result).toContain("type: 'array'");
    expect(result).toContain('template: {');
    expect(result).toContain("key: 'value'");
    expect(result).toContain("type: 'input'");
    expect(result).toContain("label: 'Tag'");
    expect(result).toContain("addButton: { label: 'Add Tag' }");
    expect(result).toContain("removeButton: { label: 'Remove' }");
    // The array field should use 'template: {' (single object), not 'template: ['
    expect(result).toMatch(/template:\s*\{/);
    expect(result).not.toMatch(/template:\s*\[/);
  });

  it('should render array template for object arrays', () => {
    const fields: FieldConfig[] = [
      {
        key: 'contacts',
        type: 'array',
        label: 'Contacts',
        template: [
          { key: 'name', type: 'input', label: 'Name' },
          { key: 'phone', type: 'input', label: 'Phone' },
        ],
        addButton: { label: 'Add Contact' },
        removeButton: { label: 'Remove' },
      },
    ];

    const result = generateFormConfig(fields, defaultOptions);

    expect(result).toContain('template: [');
    expect(result).toContain("key: 'name'");
    expect(result).toContain("key: 'phone'");
    expect(result).toContain("addButton: { label: 'Add Contact' }");
  });

  it('should render addButton: false', () => {
    const fields: FieldConfig[] = [
      {
        key: 'items',
        type: 'array',
        label: 'Items',
        template: { key: 'value', type: 'input', label: 'Item' },
        addButton: false,
      },
    ];

    const result = generateFormConfig(fields, defaultOptions);
    expect(result).toContain('addButton: false,');
  });

  it('should render removeButton: false', () => {
    const fields: FieldConfig[] = [
      {
        key: 'items',
        type: 'array',
        label: 'Items',
        template: { key: 'value', type: 'input', label: 'Item' },
        removeButton: false,
      },
    ];

    const result = generateFormConfig(fields, defaultOptions);
    expect(result).toContain('removeButton: false,');
  });

  it('should render array-level validators', () => {
    const fields: FieldConfig[] = [
      {
        key: 'tags',
        type: 'array',
        label: 'Tags',
        template: { key: 'value', type: 'input', label: 'Tag' },
        validators: [
          { type: 'minLength', value: 1 },
          { type: 'maxLength', value: 10 },
        ],
        addButton: { label: 'Add Tag' },
      },
    ];

    const result = generateFormConfig(fields, defaultOptions);
    expect(result).toContain("{ type: 'minLength', value: 1 }");
    expect(result).toContain("{ type: 'maxLength', value: 10 }");
  });

  it('should render template with validators', () => {
    const fields: FieldConfig[] = [
      {
        key: 'emails',
        type: 'array',
        label: 'Emails',
        template: {
          key: 'value',
          type: 'input',
          label: 'Email',
          props: { type: 'email' },
          validators: [{ type: 'email' }, { type: 'maxLength', value: 100 }],
        },
        addButton: { label: 'Add Email' },
      },
    ];

    const result = generateFormConfig(fields, defaultOptions);
    expect(result).toContain('template: {');
    expect(result).toContain("type: 'email'");
    expect(result).toContain("{ type: 'maxLength', value: 100 }");
  });

  it('should render addButton with props', () => {
    const fields: FieldConfig[] = [
      {
        key: 'items',
        type: 'array',
        label: 'Items',
        template: { key: 'value', type: 'input', label: 'Item' },
        addButton: { label: 'Add Item', props: { color: 'primary' } },
      },
    ];

    const result = generateFormConfig(fields, defaultOptions);
    expect(result).toContain('addButton: { label: \'Add Item\', props: { color: "primary" } }');
  });

  it('should not render template or buttons when not present', () => {
    const fields: FieldConfig[] = [
      {
        key: 'name',
        type: 'input',
        label: 'Name',
      },
    ];

    const result = generateFormConfig(fields, defaultOptions);
    expect(result).not.toContain('template');
    expect(result).not.toContain('addButton');
    expect(result).not.toContain('removeButton');
  });
});
