import type { OpenAPIV3, OpenAPIV3_1 } from 'openapi-types';
import { toInterfaceName, toPascalCase } from '../utils/naming.js';
import { isReferenceObject } from '../utils/openapi-utils.js';

type SchemaObject = OpenAPIV3.SchemaObject | OpenAPIV3_1.SchemaObject;

export interface InterfaceGeneratorOptions {
  method: string;
  path: string;
  operationId?: string;
}

export function generateInterface(schema: SchemaObject, options: InterfaceGeneratorOptions): string {
  const interfaceName = toInterfaceName(options.method, options.path, options.operationId);
  const lines: string[] = [];
  const nestedInterfaces: string[] = [];

  // Resolve the effective properties + required set, handling allOf and oneOf+discriminator
  const { properties, required } = resolveSchemaProperties(schema);

  lines.push(`export interface ${interfaceName} {`);

  for (const [name, propSchema] of properties) {
    if (isReferenceObject(propSchema)) continue;

    const optional = required.has(name) ? '' : '?';
    const tsType = schemaToTsType(name, propSchema, interfaceName, nestedInterfaces);
    lines.push(`  ${name}${optional}: ${tsType};`);
  }

  lines.push(`}`);

  if (nestedInterfaces.length > 0) {
    return `// @generated by @ng-forge/openapi-generator \n` + [...nestedInterfaces, '', ...lines, ''].join('\n');
  }

  lines.push('');
  return `// @generated by @ng-forge/openapi-generator \n` + lines.join('\n');
}

/**
 * Resolve properties and required fields from a schema, handling allOf merging
 * and oneOf+discriminator flattening so the interface generator produces
 * complete interfaces instead of empty ones.
 */
function resolveSchemaProperties(schema: SchemaObject): { properties: Array<[string, SchemaObject]>; required: Set<string> } {
  // Handle allOf — merge all constituent schemas' properties
  if (schema.allOf) {
    const merged = new Map<string, SchemaObject>();
    const allRequired = new Set<string>(schema.required ?? []);

    for (const sub of schema.allOf as SchemaObject[]) {
      if (isReferenceObject(sub)) continue;
      const resolved = resolveSchemaProperties(sub);
      for (const [name, propSchema] of resolved.properties) {
        merged.set(name, propSchema);
      }
      for (const r of resolved.required) {
        allRequired.add(r);
      }
    }

    return { properties: Array.from(merged.entries()), required: allRequired };
  }

  // Handle oneOf + discriminator — collect discriminator + all variant properties
  if (schema.oneOf && schema.discriminator) {
    const merged = new Map<string, SchemaObject>();
    const allRequired = new Set<string>(schema.required ?? []);

    // Collect discriminator values for the union type
    const discriminatorName = (schema.discriminator as { propertyName: string }).propertyName;
    const discriminatorValues: string[] = [];

    for (const variant of schema.oneOf as SchemaObject[]) {
      if (isReferenceObject(variant)) continue;
      const resolved = resolveSchemaProperties(variant);

      for (const [name, propSchema] of resolved.properties) {
        if (name === discriminatorName) {
          // Collect enum values from discriminator property
          if (propSchema.enum) {
            for (const v of propSchema.enum) {
              discriminatorValues.push(String(v));
            }
          }
          continue;
        }
        // Variant-specific properties are always optional in the union interface
        merged.set(name, propSchema);
      }
    }

    // Add discriminator property with union of all values
    if (discriminatorValues.length > 0) {
      merged.set(discriminatorName, {
        type: 'string',
        enum: discriminatorValues,
      } as SchemaObject);
    } else if (schema.properties?.[discriminatorName]) {
      const discProp = schema.properties[discriminatorName];
      if (!isReferenceObject(discProp)) {
        merged.set(discriminatorName, discProp);
      }
    }

    // Only the discriminator itself is required; variant properties are optional
    allRequired.clear();
    if (schema.required?.includes(discriminatorName)) {
      allRequired.add(discriminatorName);
    }

    // Reorder: discriminator first, then the rest
    const ordered: Array<[string, SchemaObject]> = [];
    if (merged.has(discriminatorName)) {
      ordered.push([discriminatorName, merged.get(discriminatorName)!]);
      merged.delete(discriminatorName);
    }
    for (const entry of merged.entries()) {
      ordered.push(entry);
    }

    return { properties: ordered, required: allRequired };
  }

  // Standard object — read properties directly
  const properties: Array<[string, SchemaObject]> = [];
  const required = new Set<string>(schema.required ?? []);

  for (const [name, propSchema] of Object.entries(schema.properties ?? {})) {
    if (isReferenceObject(propSchema)) continue;
    properties.push([name, propSchema]);
  }

  return { properties, required };
}

function schemaToTsType(propertyName: string, schema: SchemaObject, parentName: string, nestedInterfaces: string[]): string {
  const rawType = (schema as Record<string, unknown>)['type'];
  // Normalize OpenAPI 3.1 `type: [T, 'null']` → `type: T` and remember nullability.
  let type: string | undefined;
  let nullableFrom31Type = false;
  if (Array.isArray(rawType)) {
    const nonNull = (rawType as string[]).filter((t) => t !== 'null');
    nullableFrom31Type = nonNull.length !== rawType.length;
    type = nonNull[0];
  } else {
    type = rawType as string | undefined;
  }
  const isNullable = (schema as Record<string, unknown>)['nullable'] === true || nullableFrom31Type;
  // Filter `null` out of enum values when the type is nullable — it's handled by `| null` below.
  const enumValues = schema.enum ? schema.enum.filter((v: unknown) => v !== null) : undefined;

  if (enumValues && enumValues.length > 0) {
    const enumUnion = enumValues.map((v: unknown) => (typeof v === 'string' ? `'${v}'` : String(v))).join(' | ');
    // Enum + nullable: the union must include null (OpenAPI 3.0 nullable keyword can combine with enum).
    return isNullable ? `${enumUnion} | null` : enumUnion;
  }

  // Handle nullable (OpenAPI 3.0 and 3.1 type:[T,null])
  if (isNullable) {
    const baseSchema = { ...schema, nullable: undefined, type } as SchemaObject;
    const baseType = schemaToTsType(propertyName, baseSchema, parentName, nestedInterfaces);
    return `${baseType} | null`;
  }

  // Handle oneOf / anyOf → union
  const unionSchemas = (schema.oneOf ?? schema.anyOf) as SchemaObject[] | undefined;
  if (unionSchemas) {
    // Check if this is a discriminator schema — use mapping keys for distinct variant names
    const disc = (schema as Record<string, unknown>)['discriminator'] as
      | { propertyName: string; mapping?: Record<string, string> }
      | undefined;
    const mappingKeys = disc?.mapping ? Object.keys(disc.mapping) : undefined;

    const types = unionSchemas
      .filter((s) => !isReferenceObject(s))
      .map((s, i) => {
        if ((s.type === 'object' || s.properties) && mappingKeys) {
          const variantName = mappingKeys[i] ? toPascalCase(mappingKeys[i]) : `Variant${i + 1}`;
          const nestedName = `${parentName}${toPascalCase(propertyName)}${variantName}`;
          const nestedInterface = generateNestedInterface(nestedName, s);
          nestedInterfaces.push(nestedInterface);
          return nestedName;
        }
        return schemaToTsType(propertyName, s, parentName, nestedInterfaces);
      });
    return types.join(' | ');
  }

  // Handle allOf → intersection.
  // Each branch that is itself a union (contains `|`) must be parenthesised so the
  // intersection operator binds tighter than the outer unions. Without parens,
  // TypeScript reads `A & B | null` as `(A & B) | null`, which is looser than the
  // strict intersection semantics of allOf. With parens, `(A) & (B | null)` reduces
  // correctly: null is incompatible with A so it drops out of the intersection.
  if (schema.allOf) {
    const types = (schema.allOf as SchemaObject[])
      .filter((s) => !isReferenceObject(s))
      .map((s) => {
        const t = schemaToTsType(propertyName, s, parentName, nestedInterfaces);
        return t.includes(' | ') ? `(${t})` : t;
      });
    return types.join(' & ');
  }

  // JSON Schema / OpenAPI 3.1 allow `type: 'null'` as a standalone branch
  // (commonly seen inside oneOf / anyOf to express "X or null").
  if (type === 'null') return 'null';
  if (type === 'string') return 'string';
  if (type === 'integer' || type === 'number') return 'number';
  if (type === 'boolean') return 'boolean';

  // SchemaObject is a union; use bracket access for `items` on array schemas
  const arrayItems = (schema as Record<string, unknown>)['items'] as SchemaObject | undefined;
  if (type === 'array' && arrayItems) {
    const items = arrayItems;
    if (items.type === 'object' || items.properties) {
      const nestedName = `${parentName}${toPascalCase(propertyName)}Item`;
      const nestedInterface = generateNestedInterface(nestedName, items);
      nestedInterfaces.push(nestedInterface);
      return `${nestedName}[]`;
    }
    if (items.enum) {
      return `(${items.enum.map((v: unknown) => (typeof v === 'string' ? `'${v}'` : String(v))).join(' | ')})[]`;
    }
    return `${schemaToTsType(propertyName, items, parentName, nestedInterfaces)}[]`;
  }

  if (type === 'object' || schema.properties) {
    const nestedName = `${parentName}${toPascalCase(propertyName)}`;
    const nestedInterface = generateNestedInterface(nestedName, schema);
    nestedInterfaces.push(nestedInterface);
    return nestedName;
  }

  return 'unknown';
}

function generateNestedInterface(name: string, schema: SchemaObject): string {
  const lines: string[] = [];
  const nestedInterfaces: string[] = [];
  const required = new Set(schema.required ?? []);

  lines.push(`export interface ${name} {`);

  for (const [propName, propSchema] of Object.entries(schema.properties ?? {})) {
    if (isReferenceObject(propSchema)) continue;
    const optional = required.has(propName) ? '' : '?';
    const tsType = schemaToTsType(propName, propSchema, name, nestedInterfaces);
    lines.push(`  ${propName}${optional}: ${tsType};`);
  }

  lines.push(`}`);

  if (nestedInterfaces.length > 0) {
    return [...nestedInterfaces, '', ...lines].join('\n');
  }

  return lines.join('\n');
}
